# Generated by Django 3.2.15 on 2022-09-02 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokesafe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='pokemon',
            name='base_experience',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='height',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='is_default',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='weight',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='first_move',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pokesafe.move'),
        ),
    ]
